name: 軸屋敬介 | Keisuke Jikuya
icon: assets/images/kei.png
favicon: assets/images/favicon.ico
excerpt_separator: <!--more-->
highlighter: rouge
gems:
  - jekyll-paginate-v2
  - jekyll-toc
# Pagination Settings
pagination:
  enabled: true
  per_page: 8
  permalink: '/:num/'
  title: ' Posts | :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true