name: 軸屋敬介 | Keisuke Jikuya
icon: assets/images/kei.png
favicon: assets/images/favicon.ico
exclude: [README.md]
keep_files: [README.md, .git]
excerpt_separator: <!--more-->
highlighter: rouge
gems:
  - jekyll-paginate-v2
  - jekyll-toc
  - jekyll-sitemap
# Pagination Settings
pagination:
  enabled: true
  per_page: 8
  permalink: '/:num/'
  title: ' Posts | :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
toc:
  max_level: 2 # default: 6
url: "https://absolute-value.github.io"
sitemap:
  file: "/sitemap.xml"
  change_frequency_name: "always"
  priority_name: "0.8"